wip

diff --git a/utils/init b/utils/init
--- a/utils/init
+++ b/utils/init
@@ -199,6 +199,15 @@ sysrc -qf /tmp/initenv.conf nodeippool="${NET}" \
 
 /usr/local/cbsd/sudoexec/initenv /tmp/initenv.conf 2>&1 | tee -a /var/log/cbsd-init.log
 
+cbsd_version=$( /usr/local/bin/cbsd version 2>&1 )
+ret=$?
+if [ ${ret} -eq 0 ]; then
+	echo "CBSD version: ${cbsd_version}" | tee -a /var/log/cbsd-init.log
+else
+	echo "error: cbsd version failed"
+	exit 1
+fi
+
 if [ "${cbsd_nat}" = "1" ]; then
 	/usr/local/bin/cbsd naton 2>&1 | tee -a /var/log/cbsd-init.log
 else
